//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelkiDotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public int batch_id { get; set; }
        public string batch_name { get; set; }
    }
}
