//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelkiDotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UUID { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Mobile { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public string Batch { get; set; }
    }
}
